from typing import Literal

from pydantic import BaseModel, Field

from app.models.users import UserPublic

MessageStatus = Literal["sent", "delivered", "read"]


class Message(BaseModel):
    id: int
    conversation_id: int
    sender_id: int
    client_id: str
    kind: Literal["text", "group_update"]
    body: str | None
    # For group updates, e.g. {"action": "member_added", "target_ids": [4]}.
    meta: dict | None
    sent_at: int
    # Only on your own text messages: the furthest state any recipient reached
    # (what the bubble icon shows). null on everyone else's messages.
    status: MessageStatus | None


class SendMessageBody(BaseModel):
    # Generated by the client before sending; resending the same one never duplicates.
    client_id: str = Field(min_length=1, max_length=64)
    body: str = Field(min_length=1, max_length=10_000)


class MessagePage(BaseModel):
    messages: list[Message]  # oldest first, ready to render
    has_more: bool


class MarkReadBody(BaseModel):
    up_to_message_id: int


class MarkReadResponse(BaseModel):
    updated: int


class Receipt(BaseModel):
    user: UserPublic
    status: MessageStatus
    updated_at: int
