-- Signal clone schema (SQLite).
-- Conventions (see DECISIONS.md D-8):
--   * ids are AUTOINCREMENT so they are never reused and strictly increase;
--     messages.id is the timeline ordering key.
--   * all times are INTEGER milliseconds since the Unix epoch, UTC.
-- Foreign keys are only enforced because connection.py runs PRAGMA foreign_keys = ON.

CREATE TABLE IF NOT EXISTS users (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    phone_number  TEXT    NOT NULL UNIQUE CHECK (phone_number GLOB '+[0-9]*'),
    username      TEXT    UNIQUE COLLATE NOCASE,
    given_name    TEXT    NOT NULL CHECK (length(trim(given_name)) > 0),
    family_name   TEXT,
    about         TEXT,
    avatar_path   TEXT,
    avatar_color  TEXT    NOT NULL CHECK (avatar_color IN (
                      'A100','A110','A120','A130','A140','A150',
                      'A160','A170','A180','A190','A200','A210')),
    -- Mocked presence (D-12). "Online" is derived from live WebSockets, never stored.
    last_seen_at  INTEGER,
    created_at    INTEGER NOT NULL
);

-- Only a hash of the bearer token is stored, so a leaked DB can't be replayed (D-9).
CREATE TABLE IF NOT EXISTS sessions (
    token_hash    TEXT    PRIMARY KEY,
    user_id       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at    INTEGER NOT NULL,
    last_used_at  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);

CREATE TABLE IF NOT EXISTS contacts (
    owner_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    contact_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at  INTEGER NOT NULL,
    PRIMARY KEY (owner_id, contact_id),
    CHECK (owner_id <> contact_id)
);

-- One table for 1:1 and group chats (D-5).
CREATE TABLE IF NOT EXISTS conversations (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    type          TEXT    NOT NULL CHECK (type IN ('direct', 'group')),
    -- "<smaller user id>:<larger user id>" for direct chats; UNIQUE makes a second
    -- chat between the same pair impossible. NULL for groups (UNIQUE ignores NULLs).
    direct_key    TEXT    UNIQUE,
    name          TEXT,
    avatar_path   TEXT,
    avatar_color  TEXT    CHECK (avatar_color IS NULL OR avatar_color IN (
                      'A100','A110','A120','A130','A140','A150',
                      'A160','A170','A180','A190','A200','A210')),
    created_by    INTEGER NOT NULL REFERENCES users(id),
    created_at    INTEGER NOT NULL,
    CHECK ((type = 'direct') = (direct_key IS NOT NULL)),
    -- Group-only columns must stay empty on direct chats, and groups need a name.
    CHECK (type = 'group' OR (name IS NULL AND avatar_path IS NULL AND avatar_color IS NULL)),
    CHECK (type = 'direct' OR (name IS NOT NULL AND length(trim(name)) > 0))
);

CREATE TABLE IF NOT EXISTS conversation_members (
    conversation_id  INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    user_id          INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role             TEXT    NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'member')),
    joined_at        INTEGER NOT NULL,
    -- NULL = active. Removal is a soft delete so the user keeps read-only history (D-10).
    left_at          INTEGER,
    PRIMARY KEY (conversation_id, user_id)
);
-- The PK starts with conversation_id, so it can't serve "all chats of user X",
-- which is the chat-list query.
CREATE INDEX IF NOT EXISTS idx_members_user ON conversation_members(user_id, conversation_id);

CREATE TABLE IF NOT EXISTS messages (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    conversation_id  INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id        INTEGER NOT NULL REFERENCES users(id),
    -- Generated by the client before sending; lets a retried send be recognised
    -- instead of stored twice.
    client_id        TEXT    NOT NULL,
    kind             TEXT    NOT NULL DEFAULT 'text' CHECK (kind IN ('text', 'group_update')),
    body             TEXT,
    -- JSON describing a group update, e.g. {"action":"member_added","target_ids":[4]} (D-11).
    meta             TEXT,
    sent_at          INTEGER NOT NULL,
    UNIQUE (sender_id, client_id),
    CHECK (kind <> 'text' OR (body IS NOT NULL AND length(body) > 0)),
    CHECK (kind <> 'group_update' OR meta IS NOT NULL)
);
-- History pages and "last message per chat" are range scans on this index.
CREATE INDEX IF NOT EXISTS idx_messages_conv ON messages(conversation_id, id);

-- One row per recipient per message (D-6). Status: 1 = sent, 2 = delivered, 3 = read.
-- "sending" and "failed" never reach the DB; they are client-only states.
CREATE TABLE IF NOT EXISTS message_receipts (
    message_id    INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    recipient_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status        INTEGER NOT NULL CHECK (status IN (1, 2, 3)),
    updated_at    INTEGER NOT NULL,
    PRIMARY KEY (message_id, recipient_id)
);
-- Serves "mark everything delivered for user X" on connect and unread counts (status < 3).
CREATE INDEX IF NOT EXISTS idx_receipts_recipient ON message_receipts(recipient_id, status);
