// Tracks sends that haven't been acked yet, keyed by client_id (generated by the sender —
// protocol doc). Deliberately in-memory only, not localStorage: Signal persists an unsent
// outbox across restarts, but this clone accepts losing it on reload for simplicity (DECISIONS.md).
// This store holds no socket reference; lib/ws/realtime.ts reads and writes it and owns the
// actual send/retry/timeout orchestration, so this file stays a plain, testable data store.
import { create } from "zustand";

export interface OutboxEntry {
  conversationId: number;
  clientId: string;
  body: string;
  /** The 15s ack-timeout handle (protocol doc's "no ack after a timeout, then retry"). */
  timer: ReturnType<typeof setTimeout> | null;
}

interface OutboxState {
  pending: Record<string, OutboxEntry>;
  add: (entry: OutboxEntry) => void;
  remove: (clientId: string) => void;
  setTimer: (clientId: string, timer: ReturnType<typeof setTimeout> | null) => void;
}

export const useOutbox = create<OutboxState>((set) => ({
  pending: {},

  add: (entry) => set((state) => ({ pending: { ...state.pending, [entry.clientId]: entry } })),

  remove: (clientId) =>
    set((state) => {
      const { [clientId]: removed, ...rest } = state.pending;
      if (removed?.timer) clearTimeout(removed.timer);
      return { pending: rest };
    }),

  setTimer: (clientId, timer) =>
    set((state) => {
      const entry = state.pending[clientId];
      if (!entry) return state;
      if (entry.timer) clearTimeout(entry.timer);
      return { pending: { ...state.pending, [clientId]: { ...entry, timer } } };
    }),
}));
